options:
    # Changes the default messages' behavior:
    #   keep (default) - does nothing to the default messages
    #   remove - removes the default message (still allowing other plugins to set their own message)
    #   forceRemove - removes the message completly
    #       technical note: plugins that don't use the deathMessage property
    #                       of playerDeathEvent can still display their own messages
    defaultMessageMode: keep
    
    # How do you want the Awesome Messages displayed?
    #   classic (default) - displays a line with some awesome information about the killing weapon
    #   face - attemtps to draw the killed player's skin (head) in chat
    #   none - no awesomness: turns off the custom death messages. Why are you using this plugin again?
    awesomeDeathMessages: classic
